### ISSUE TITLE
Still on management commands.

### ISSUE THREAD

**Issue by gtoffoli** [devkral/rdflib-django3#6]
Hi, #devkral,
I was working on the management commands too. You've done it before. Thank you!
However, I'm not able to use your version without a few further patches. Please, tell me if I am wrong.

Without my patches to **rdf_import**, I'm getting the following errors:

```
python manage.py rdf_import rdf_import-200529.n3 --format n3
=> manage.py rdf_import: error: unrecognized arguments: rdf_import-200529.n3
python manage.py rdf_import --format n3 rdf_import-200529.n3
=> manage.py rdf_import: error: unrecognized arguments: rdf_import-200529.n3
python manage.py rdf_import --format n3 < rdf_import-200529.n3
=> CommandError: No file or resource specified.
```

Without my patches to **rdf_export**, I'm getting the following errors:

```
python manage.py rdf_export rdf_export-200529.n3 --format n3
=> manage.py rdf_export: error: unrecognized arguments: rdf_export-200529.n3
python manage.py rdf_export --format n3 rdf_export-200529.n3
=> manage.py rdf_export: error: unrecognized arguments: rdf_export-200529.n3
python manage.py rdf_export --format n3
>> Traceback (most recent call last):
...
  File "C:\commons321\lib\site-packages\rdflib\plugins\serializers\turtle.py", line 156, in write
    self.stream.write(text.encode(self.encoding, 'replace'))
TypeError: write() argument must be str, not bytes
python manage.py rdf_export --format n3 > rdf_export-200529.n3
>> Traceback (most recent call last):
...
  File "C:\commons321\lib\site-packages\rdflib\plugins\serializers\turtle.py", line 156, in write
    self.stream.write(text.encode(self.encoding, 'replace'))
TypeError: write() argument must be str, not bytes
```
With my corrections, I can do everything, except exporting through an os pipe; but I think that's another problem.

It seems that implementing (or emulating?) _positional arguments_ for commands is very tricky in recent Django versions. In fact, I think that resorting to _dash-style options_ would be more simple and clear (user friendly) also for i/o filepath arguments.
In any case, my version is in the fork at https://github.com/gtoffoli/rdflib-django3 .

NOTE: I'm developing with Python 3.5 and Django 2.1, on Windows 10; will put in production on Ubuntu.

Best, Giovanni

**Comment by devkral** [comment]
nice, I see you had some very cool changes. Can you make a pull request? Or can I pull your changes?
And sorry, I didn't test correctly.

**Comment by devkral** [comment]
thanks a lot.
