### ISSUE TITLE
Falsy literals are treated as variables 

### ISSUE THREAD

**Issue by eilmiv** [devkral/rdflib-django3#9]
The following test fails:
```py
def test_falsy_literals(self):
    self.graph.add((artis, EX["prop"], Literal("")))
    self.graph.add((artis, EX["prop"], Literal(False)))

    self.assertEquals(
        list(self.graph.triples((artis, EX["prop"], Literal("")))),
        [(artis, EX["prop"], Literal(""))]
    )

    self.graph.remove((artis, EX["prop"], Literal("")))
    self.assertEquals(
        list(self.graph),
        [(artis, EX["prop"], Literal(False))]
    )
```
Because...
- it crashes because it tries to use an `URIStatement` for the falsy literal
- it returns all triples
- it removes all triples

This is the same kind of bug as in https://github.com/RDFLib/rdflib/issues/2621.

**Comment by devkral** [comment]
Tell me if there are still problems, I uploaded a new version

**Comment by eilmiv** [comment]
> Tell me if there are still problems, I uploaded a new version

I'll do that, but everything seems to work smoothly for now. Thanks for the quick fix.
